package com.aegis.erp.modules.planilla.empleado;
import com.aegis.erp.common.exception.*;
import com.aegis.erp.common.export.DocumentExportService;
import com.aegis.erp.modules.planilla.entity.*;
import com.aegis.erp.modules.planilla.repository.*;
import com.aegis.erp.modules.seguridad.sucursal.repository.SucursalRepository;
import com.aegis.erp.modules.seguridad.usuario.entity.Sucursal;
import java.time.*;
import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service public class EmpleadoService {
 private final EmpleadoRepository empleados;private final PersonaRepository personas;private final SucursalRepository sucursales;private final PuestoRepository puestos;private final StatusEmpleadoRepository status;private final FlujoStatusEmpleadoRepository flujos;private final DocumentExportService exports;private final Clock clock;
 public EmpleadoService(EmpleadoRepository empleados,PersonaRepository personas,SucursalRepository sucursales,PuestoRepository puestos,StatusEmpleadoRepository status,FlujoStatusEmpleadoRepository flujos,DocumentExportService exports,Clock clock){this.empleados=empleados;this.personas=personas;this.sucursales=sucursales;this.puestos=puestos;this.status=status;this.flujos=flujos;this.exports=exports;this.clock=clock;}
 @Transactional(readOnly=true) public List<EmpleadoResponse> listar(String search){String q=normalize(search);return empleados.findAll().stream().map(this::response).filter(x->q.isEmpty()||searchable(x).contains(q)).toList();}
 @Transactional(readOnly=true) public EmpleadoResponse obtener(Long id){return response(find(id));}
 @Transactional public EmpleadoResponse crear(EmpleadoRequest r,String user){Empleado e=Empleado.crear(persona(r.personaId()),sucursal(r.sucursalId()),r.fechaContratacion(),puesto(r.puestoId()),estado(r.statusId()),r.ingresoSueldoBase(),r.ingresoBonificacionDecreto(),r.ingresoOtrosIngresos(),r.descuentoIgss(),r.descuentoIsr(),r.descuentoInasistencias(),user,LocalDateTime.now(clock));return save(e,"No fue posible crear el empleado por una restricción de integridad.");}
 @Transactional public EmpleadoResponse modificar(Long id,EmpleadoRequest r,String user){Empleado e=find(id);if(!Objects.equals(e.getStatus().getId(),r.statusId())&&!flujos.existsById(new FlujoStatusEmpleadoId(e.getStatus().getId(),r.statusId())))throw new BusinessConflictException("El cambio de status seleccionado no está permitido por el flujo configurado.");e.modificar(persona(r.personaId()),sucursal(r.sucursalId()),r.fechaContratacion(),puesto(r.puestoId()),estado(r.statusId()),r.ingresoSueldoBase(),r.ingresoBonificacionDecreto(),r.ingresoOtrosIngresos(),r.descuentoIgss(),r.descuentoIsr(),r.descuentoInasistencias(),user,LocalDateTime.now(clock));return save(e,"No fue posible actualizar el empleado por una restricción de integridad.");}
 @Transactional public void eliminar(Long id){Empleado e=find(id);try{empleados.delete(e);empleados.flush();}catch(DataIntegrityViolationException ex){throw new BusinessConflictException("No se puede eliminar el empleado porque tiene información asociada.");}}
 @Transactional(readOnly=true) public List<EmpleadoOptionResponse> personas(String search){String q=normalize(search);return personas.findAll().stream().filter(x->q.isEmpty()||(x.getId()+" "+x.getNombre()+" "+x.getApellido()).toLowerCase(Locale.ROOT).contains(q)).limit(50).map(x->new EmpleadoOptionResponse(x.getId(),x.getNombre()+" "+x.getApellido())).toList();}
 @Transactional(readOnly=true) public List<EmpleadoOptionResponse> sucursales(){return sucursales.findAll().stream().map(x->new EmpleadoOptionResponse(x.getId(),x.getNombre())).toList();}
 @Transactional(readOnly=true) public List<EmpleadoOptionResponse> puestos(){return puestos.findAll().stream().map(x->new EmpleadoOptionResponse(x.getId(),x.getNombre()+" — "+x.getDepartamento().getNombre())).toList();}
 @Transactional(readOnly=true) public List<EmpleadoOptionResponse> estados(){return status.findAll().stream().map(x->new EmpleadoOptionResponse(x.getId(),x.getNombre())).toList();}
 @Transactional(readOnly=true) public List<EmpleadoOptionResponse> statusPermitidos(Long empleadoId){Empleado e=find(empleadoId);List<EmpleadoOptionResponse> out=new ArrayList<>();out.add(new EmpleadoOptionResponse(e.getStatus().getId(),e.getStatus().getNombre()));flujos.findAll().stream().filter(f->Objects.equals(f.getStatusActual().getId(),e.getStatus().getId())).map(FlujoStatusEmpleado::getStatusNuevo).filter(s->out.stream().noneMatch(o->Objects.equals(o.id(),s.getId()))).map(s->new EmpleadoOptionResponse(s.getId(),s.getNombre())).forEach(out::add);return out;}
 @Transactional(readOnly=true) public byte[] excel(String search){return exports.excel("Empleados",headers(),rows(search));}@Transactional(readOnly=true) public byte[] pdf(String search){return exports.pdf("Listado de empleados",headers(),rows(search));}
 private EmpleadoResponse save(Empleado e,String message){try{return response(empleados.saveAndFlush(e));}catch(DataIntegrityViolationException ex){throw new BusinessConflictException(message);}}
 private List<String> headers(){return List.of("ID","Persona","Sucursal","Puesto","Status","Contratación","Sueldo base","Bonificación","Otros ingresos","IGSS","ISR","Inasistencias");}
 private List<List<?>> rows(String search){return listar(search).stream().<List<?>>map(x->List.of(x.id(),x.personaNombre(),x.sucursalNombre(),x.puestoNombre(),x.statusNombre(),x.fechaContratacion(),x.ingresoSueldoBase(),x.ingresoBonificacionDecreto(),x.ingresoOtrosIngresos(),x.descuentoIgss(),x.descuentoIsr(),x.descuentoInasistencias())).toList();}
 private EmpleadoResponse response(Empleado x){return new EmpleadoResponse(x.getId(),x.getPersona().getId(),x.getPersona().getNombre()+" "+x.getPersona().getApellido(),x.getSucursal().getId(),x.getSucursal().getNombre(),x.getFechaContratacion(),x.getPuesto().getId(),x.getPuesto().getNombre(),x.getPuesto().getDepartamento().getNombre(),x.getStatus().getId(),x.getStatus().getNombre(),x.getIngresoSueldoBase(),x.getIngresoBonificacionDecreto(),x.getIngresoOtrosIngresos(),x.getDescuentoIgss(),x.getDescuentoIsr(),x.getDescuentoInasistencias());}
 private Empleado find(Long id){return empleados.findById(id).orElseThrow(()->new ResourceNotFoundException("Empleado no encontrado."));}private Persona persona(Long id){return personas.findById(id).orElseThrow(()->new ResourceNotFoundException("Persona no encontrada."));}private Sucursal sucursal(Long id){return sucursales.findById(id).orElseThrow(()->new ResourceNotFoundException("Sucursal no encontrada."));}private Puesto puesto(Long id){return puestos.findById(id).orElseThrow(()->new ResourceNotFoundException("Puesto no encontrado."));}private StatusEmpleado estado(Long id){return status.findById(id).orElseThrow(()->new ResourceNotFoundException("Status de empleado no encontrado."));}
 private String normalize(String v){return v==null?"":v.trim().toLowerCase(Locale.ROOT);}private String searchable(EmpleadoResponse x){return (x.id()+" "+x.personaNombre()+" "+x.sucursalNombre()+" "+x.puestoNombre()+" "+x.departamentoNombre()+" "+x.statusNombre()).toLowerCase(Locale.ROOT);}
}
