package com.aegis.erp.modules.planilla.empleado;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import com.aegis.erp.common.exception.BusinessConflictException;import com.aegis.erp.common.export.DocumentExportService;import com.aegis.erp.modules.planilla.entity.*;import com.aegis.erp.modules.planilla.repository.*;import com.aegis.erp.modules.seguridad.sucursal.repository.SucursalRepository;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.dao.DataIntegrityViolationException;
@ExtendWith(MockitoExtension.class)class EmpleadoServiceTest{
 @Mock EmpleadoRepository empleados;@Mock PersonaRepository personas;@Mock SucursalRepository sucursales;@Mock PuestoRepository puestos;@Mock StatusEmpleadoRepository status;@Mock FlujoStatusEmpleadoRepository flujos;@Mock DocumentExportService exports;EmpleadoService service;
 @BeforeEach void setup(){service=new EmpleadoService(empleados,personas,sucursales,puestos,status,flujos,exports,Clock.fixed(Instant.parse("2026-09-22T12:00:00Z"),ZoneOffset.UTC));}
 @Test void rechazaTransicionNoConfigurada(){Empleado e=mock(Empleado.class);StatusEmpleado actual=mock(StatusEmpleado.class);when(actual.getId()).thenReturn(1L);when(e.getStatus()).thenReturn(actual);when(empleados.findById(7L)).thenReturn(Optional.of(e));when(flujos.existsById(new FlujoStatusEmpleadoId(1L,2L))).thenReturn(false);assertThrows(BusinessConflictException.class,()->service.modificar(7L,request(2L),"admin"));verify(e,never()).modificar(any(),any(),any(),any(),any(),any(),any(),any(),any(),any(),any(),any(),any());}
 @Test void statusPermitidosDerivanDeFlujoEIncluyenActual(){Empleado e=mock(Empleado.class);StatusEmpleado actual=status(1L,"Activo"),destino=status(3L,"Suspendido"),otro=mock(StatusEmpleado.class);when(otro.getId()).thenReturn(4L);when(e.getStatus()).thenReturn(actual);when(empleados.findById(7L)).thenReturn(Optional.of(e));FlujoStatusEmpleado valido=mock(FlujoStatusEmpleado.class),ajeno=mock(FlujoStatusEmpleado.class);when(valido.getStatusActual()).thenReturn(actual);when(valido.getStatusNuevo()).thenReturn(destino);when(ajeno.getStatusActual()).thenReturn(otro);when(flujos.findAll()).thenReturn(List.of(valido,ajeno));var result=service.statusPermitidos(7L);assertEquals(List.of(1L,3L),result.stream().map(EmpleadoOptionResponse::id).toList());}
 @Test void traduceConflictoReferencialEnBaja(){Empleado e=mock(Empleado.class);when(empleados.findById(1L)).thenReturn(Optional.of(e));doThrow(new DataIntegrityViolationException("FK")).when(empleados).flush();assertThrows(BusinessConflictException.class,()->service.eliminar(1L));}
 private EmpleadoRequest request(Long statusId){BigDecimal n=new BigDecimal("1.00");return new EmpleadoRequest(1L,1L,LocalDate.of(2026,1,1),1L,statusId,n,n,n,n,n,n);}private StatusEmpleado status(Long id,String nombre){StatusEmpleado s=mock(StatusEmpleado.class);lenient().when(s.getId()).thenReturn(id);lenient().when(s.getNombre()).thenReturn(nombre);return s;}
}
